import type { NotificationChannel, StrategyMetric, StrategySignal, TradeRecord } from "@/lib/types";

export const demoSignals: StrategySignal[] = [
  {
    id: "sig_001",
    signalId: "SMC_PRO:BINANCE:BTCUSDT:5m:demo:long",
    strategy: "SMC PRO",
    version: "0.3.0",
    symbol: "BINANCE:BTCUSDT",
    timeframe: "5m",
    side: "long",
    entry: 63450.5,
    stopLoss: 63100,
    takeProfit: 64151.5,
    rr: 2,
    status: "open",
    reasons: ["Sweep Low", "Bullish CHoCH", "HTF Bull"],
    confidence: 82,
    createdAt: "2026-04-18T09:15:00+08:00",
  },
  {
    id: "sig_002",
    signalId: "SMC_PRO:BINANCE:ETHUSDT:15m:demo:short",
    strategy: "SMC PRO",
    version: "0.3.0",
    symbol: "BINANCE:ETHUSDT",
    timeframe: "15m",
    side: "short",
    entry: 3168.4,
    stopLoss: 3194.2,
    takeProfit: 3116.8,
    rr: 2,
    status: "won",
    reasons: ["Sweep High", "Bearish CHoCH", "Risk OK"],
    confidence: 76,
    createdAt: "2026-04-18T08:30:00+08:00",
  },
  {
    id: "sig_003",
    signalId: "SMC_PRO:BINANCE:SOLUSDT:1h:demo:short",
    strategy: "SMC PRO",
    version: "0.3.0",
    symbol: "BINANCE:SOLUSDT",
    timeframe: "1h",
    side: "short",
    entry: 144.22,
    stopLoss: 147.1,
    takeProfit: 138.46,
    rr: 2,
    status: "lost",
    reasons: ["Sweep High", "Bearish CHoCH", "Cooldown OK"],
    confidence: 63,
    createdAt: "2026-04-17T18:00:00+08:00",
  },
];

export const demoTrades: TradeRecord[] = [
  {
    id: "tr_001",
    signalId: demoSignals[1].signalId,
    symbol: "BINANCE:ETHUSDT",
    side: "short",
    entryPrice: 3168.4,
    exitPrice: 3118.2,
    stopLoss: 3194.2,
    takeProfit: 3116.8,
    positionSize: 0.8,
    fee: 4.8,
    pnl: 35.36,
    pnlR: 1.94,
    status: "closed",
    emotion: "平穩",
    mistakeTags: [],
    notes: "照計畫出場，未提前移動停損。",
    openedAt: "2026-04-18T08:31:00+08:00",
    closedAt: "2026-04-18T09:20:00+08:00",
  },
  {
    id: "tr_002",
    signalId: demoSignals[0].signalId,
    symbol: "BINANCE:BTCUSDT",
    side: "long",
    entryPrice: 63460,
    stopLoss: 63100,
    takeProfit: 64151.5,
    positionSize: 0.05,
    fee: 3.2,
    pnl: 0,
    pnlR: 0,
    status: "open",
    emotion: "耐心等待",
    mistakeTags: [],
    notes: "等待第一段推進後觀察是否減倉。",
    openedAt: "2026-04-18T09:17:00+08:00",
  },
];

export const demoMetrics: StrategyMetric[] = [
  { label: "今日訊號", value: "0", detail: "等待 TradingView webhook", tone: "neutral" },
  { label: "資料源", value: "Binance", detail: "Spot public market data", tone: "good" },
  { label: "策略版本", value: "0.3.0", detail: "HTF / ATR / risk filters", tone: "good" },
  { label: "最大回撤", value: "-", detail: "累積交易後計算", tone: "warning" },
];

export const demoChannels: NotificationChannel[] = [
  { id: "ch_telegram", platform: "telegram", label: "Telegram Bot", enabled: true, lastDelivery: "已設定" },
  { id: "ch_line", platform: "line", label: "LINE Official Account", enabled: false, lastDelivery: "尚未綁定" },
  { id: "ch_push", platform: "push", label: "PWA Push", enabled: false, lastDelivery: "待設定 FCM" },
];
